apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretKey.name }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{ .Values.secretKey.key }}: {{ randAlphaNum 20 | b64enc }}